### ISSUE TITLE
Any::Moose is deprecated

### ISSUE THREAD

**Issue by fibo** [avar/bot-training#2]
Since [Any::Moose](https://metacpan.org/pod/Any::Moose) is deprecated I created a [moose](https://github.com/avar/bot-training/tree/moose) branch where it is possible to test a port to Moose or Moo.

**Comment by fibo** [comment]
Removed deprecated stuff: Mouse and Class::MOP::load_class.

Command `dzil test` passes.

Branch _moose_ could be merged into _master_.

**Comment by avar** [comment]
Cool, Just Do It. Also release it when you're done :) I trust you man.
